name: social_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Firebase
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.10

  # Loading
  card_loading: ^0.1.3
  flutter_spinkit: ^5.1.0

  # Spash Screen
  easy_splash_screen: ^1.0.3

  # Conditional Builder
  conditional_builder_null_safety: ^0.0.6

  # Image Picker
  image_picker: ^0.8.4+11

  # Local Storag Shared Preferences
  shared_preferences: ^2.0.13

  # Bloc Provider
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  # Responsive Screen
  sizer: ^2.0.15

  # Toast
  fluttertoast: ^8.0.9
  oktoast: ^3.1.5

  # Font Google
  google_fonts: ^2.3.1

  # Flutter Launcher Icons
  flutter_launcher_icons: "^0.9.2"

  # Add real-time voice and video communications through a simple and powerful SDK
  agora_rtc_engine: ^5.1.0
  permission_handler: ^9.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "Asset/Images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - Asset/Images/
